NM_PARAM_STRING = 1;
NM_PARAM_INT32  = 2;
NM_PARAM_FLOAT  = 3;
NM_PARAM_BINARY = 4;

global.GAME_UPDATE_CLIENT_COUNT = 1;
global.GAME_UPDATE_PLAYER_POS = 2;
global.GAME_PLAYER_SET_UID = 3;
global.GAME_PLAYER_JOINED =4;
global.GAME_PLAYER_LEFT = 5;
global.GAME_PLAYER_QUEUE = 6;
global.GAME_START = 7;
global.GAME_PLAYER_CANCEL_QUEUE = 8;
global.GAME_PLAYER_FIRE = 9;
global.GAME_OVER = 10;
global.GAME_PLAYER_SURRENDER = 11;
global.GAME_SPAWN_ITEM = 12;
global.GAME_UPDATE_PLAYERLIKE_PET = 13;
